# Generated by Django 4.1 on 2022-10-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Character',
        ),
    ]
